variables:
  # Runner will discover the UID and GID of the user configured in the image used by the build container
  # and will change the ownership of the working directory and files by running the chmod command in the
  # predefined container (after updating sources, restoring cache and downloading artifacts).
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

default:
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build-docker-image:
  stage: .pre
  services:
    - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:dind
      variables:
        DOCKER_TLS_CERTDIR: ""
      # hostname of dind container inside the private network has to be "docker"
      alias: docker
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login $CI_DEPENDENCY_PROXY_SERVER -u $CI_DEPENDENCY_PROXY_USER --password-stdin

    - docker build
      --pull
      --push
      --cache-from $CI_REGISTRY_IMAGE:buildcache
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-arg REPO=amd64
      --build-arg UBUNTU_RELEASE=noble
      --build-arg ASMCOV_URI="$ASMCOV_URI"
      --tag $CI_REGISTRY_IMAGE:buildcache
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -f ci/Dockerfile .

Build:
  stage: build
  script:
    - env
    - ci/build.sh
    - ci/build.sh Debug --asan
    - ci/build.sh coverage --gcov
  artifacts:
    paths:
      - build/
      - result/

Build Doc:
  stage: build
  script:
    - ci/build_doc.sh
  artifacts:
    paths:
      - result/

Lint:
  stage: test
  script:
    - ci/clang-tidy.sh
    - ci/lint-scripts.sh
    - ci/format-code.sh --check
    - ci/lint-commits.sh origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
    - ci/readme-toc.sh

Unit Tests:
  stage: test
  script:
    - ci/run-utests.sh
    - ci/run-utests.sh Debug
    - ci/run-utests.sh coverage
  artifacts:
    when: always
    paths:
      - result/amd64/utest_report.txt
      - result/amd64-Debug/utest_report.txt
      - result/amd64-coverage/utest_report.txt
      - build/amd64-coverage/**/*.gcda
      - build/amd64-coverage/**/*.gcno

code-coverage:
  tags:
    - "intelpt"
    - "docker"
  stage: test
  needs:
    - Build
    - Unit Tests
  script:
      - ci/create_coverage.sh asmcov
      - ci/create_coverage.sh gcov
  artifacts:
    when: always
    paths:
      - build/*/results/coverage

Smoke Tests:
  stage: test
  script:
    - ci/run-smoketests.sh
    - ci/run-smoketests.sh Debug
  artifacts:
    when: always
    paths:
      - result/amd64/smoketests
      - result/amd64-Debug/smoketests

Integration Tests:
  stage: test
  needs:
    - build-docker-image
  services:
    - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:dind
      variables:
        DOCKER_TLS_CERTDIR: ""
      # hostname of dind container inside the private network has to be "docker"
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y docker.io
  script:
    - ci/run-integration-tests.sh
  artifacts:
    when: always
    paths:
      - result/
